export const STATIC_BRANDS = [
  {
    id: 1,
    slug: "dew-motors",
    name: "Dew Motors",
    tagline: "Power Your Ride, Go Electric",
    description:
      "Sri Lanka's leading electric motorcycle brand, offering eco-friendly, powerful electric bikes designed for daily commuting.",
    primaryColor: "#0ea5e9",
    accentColor: "#38bdf8",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 2,
    slug: "dew-plus",
    name: "Dew Plus",
    tagline: "Crystal Clear Entertainment",
    description:
      "Premium 4K Android Smart TVs with built-in streaming apps, crystal clear displays, and immersive sound systems.",
    primaryColor: "#8b5cf6",
    accentColor: "#a78bfa",
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 3,
    slug: "dew-plus-ac",
    name: "DEW+ AC",
    tagline: "Cool Comfort, Smart Living",
    description:
      "Energy-efficient inverter split air conditioners with R32 eco-friendly refrigerant and smart WiFi control.",
    primaryColor: "#06b6d4",
    accentColor: "#22d3ee",
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 4,
    slug: "manju-dew-super",
    name: "Manju Dew Super",
    tagline: "Pure Water, Healthy Life",
    description:
      "Advanced RO, UV, and UF filtration technology delivering clean, safe drinking water for Sri Lankan homes.",
    primaryColor: "#3b82f6",
    accentColor: "#60a5fa",
    sortOrder: 4,
    isActive: true,
  },
  {
    id: 5,
    slug: "manju-exercise-books",
    name: "Manju Exercise Books",
    tagline: "Write Your Success Story",
    description:
      "Trusted by students across Sri Lanka for quality, durability, and value in every ruling and size.",
    primaryColor: "#f59e0b",
    accentColor: "#fbbf24",
    sortOrder: 5,
    isActive: true,
  },
];

export const STATIC_PRODUCTS = [
  {
    id: 1,
    slug: "dew-em005-2400w",
    name: "Dew EM005 2400W Electric Bike",
    shortDescription: "Powerful 2400W electric motorcycle with 80km range",
    description:
      "The Dew EM005 is our flagship electric motorcycle, engineered for Sri Lankan roads. Powered by a 2400W brushless DC motor and a high-capacity 72V 32Ah lithium battery, it delivers a smooth, powerful ride with an 80km range on a single charge. Built with a lightweight alloy frame, hydraulic disc brakes, and LED lighting throughout, the EM005 is the perfect blend of performance and eco-conscious commuting. Comes with a 2-year battery warranty and island-wide service support.",
    brandName: "Dew Motors",
    brandId: 1,
    categoryId: 1,
    category: "Electric Bikes",
    basePrice: "485000.00",
    salePrice: "449000.00",
    discount: 7,
    currency: "LKR",
    isInStock: true,
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    imageUrl: "/scooter_red.png",
    specifications: JSON.stringify({
      "Motor Power": "2400W Brushless DC",
      Battery: "72V 32Ah Lithium-Ion",
      Range: "80 km per charge",
      "Top Speed": "80 km/h",
      "Charging Time": "6–8 hours",
      "Frame Material": "Lightweight Alloy",
      Brakes: "Hydraulic Disc (Front & Rear)",
      Weight: "138 kg",
      Lighting: "Full LED",
      Warranty: "2 years (battery), 1 year (motor)",
    }),
  },
  {
    id: 2,
    slug: "dew-yw06-2000w",
    name: "Dew YW06 2000W Electric Bike",
    shortDescription: "Affordable 2000W electric bike with 60km range",
    description:
      "The Dew YW06 brings premium electric mobility at an accessible price point. Equipped with a 2000W motor and a 60V 28Ah battery pack, this bike covers up to 60km on a full charge — ideal for daily city and suburban commutes. Its semi-automatic design makes it easy to ride for beginners, while the reinforced steel frame ensures long-term durability. LED headlights, digital instrument cluster, and a comfortable cushioned seat complete the package.",
    brandName: "Dew Motors",
    brandId: 1,
    categoryId: 1,
    category: "Electric Bikes",
    basePrice: "365000.00",
    salePrice: "339000.00",
    discount: 7,
    currency: "LKR",
    isInStock: true,
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    imageUrl: "/scooter_silver.png",
    specifications: JSON.stringify({
      "Motor Power": "2000W Brushless DC",
      Battery: "60V 28Ah Lithium-Ion",
      Range: "60 km per charge",
      "Top Speed": "70 km/h",
      "Charging Time": "6–7 hours",
      "Frame Material": "High-strength Steel",
      Brakes: "Mechanical Disc (Front & Rear)",
      Weight: "125 kg",
      Lighting: "LED Headlight & Tail Light",
      Warranty: "1 year (battery & motor)",
    }),
  },
  {
    id: 3,
    slug: "dew-em003-1500w-scooter",
    name: "Dew EM003 Electric Scooter",
    shortDescription: "Compact 1500W electric scooter for city rides",
    description:
      "The Dew EM003 Electric Scooter is the ultimate urban commuter — lightweight, nimble, and zero-emission. Its 1500W motor and 48V 20Ah battery deliver up to 50km of range, perfect for navigating busy city streets. The compact design fits easily into tight parking spaces, while the removable battery allows convenient home charging. Built for those who want a smarter, greener way to get around Colombo and beyond.",
    brandName: "Dew Motors",
    brandId: 1,
    categoryId: 1,
    category: "Electric Bikes",
    basePrice: "245000.00",
    salePrice: null,
    discount: 0,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    imageUrl:
      "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=400&q=80",
    specifications: JSON.stringify({
      "Motor Power": "1500W Brushless DC",
      Battery: "48V 20Ah Lithium-Ion (Removable)",
      Range: "50 km per charge",
      "Top Speed": "55 km/h",
      "Charging Time": "4–5 hours",
      "Frame Material": "Aluminium Alloy",
      Brakes: "Front Disc / Rear Drum",
      Weight: "98 kg",
      Lighting: "LED",
      Warranty: "1 year",
    }),
  },
  {
    id: 4,
    slug: "dew-plus-32-hd-smart-tv",
    name: 'Dew Plus 32" HD Smart TV',
    shortDescription: "32-inch HD Android Smart TV with built-in apps",
    description:
      'The Dew Plus 32" Smart TV brings vibrant HD entertainment to your living room. Running Android TV, it gives you access to Netflix, YouTube, Disney+, and thousands of other apps right out of the box. The 32-inch HD display delivers crisp, vivid visuals with a built-in 10W stereo speaker system for rich audio. With HDMI, USB, and WiFi connectivity, this TV is the smart entertainment hub your home deserves — at an unbeatable price.',
    brandName: "Dew Plus",
    brandId: 2,
    categoryId: 2,
    category: "Smart TVs",
    basePrice: "54900.00",
    salePrice: "49900.00",
    discount: 9,
    currency: "LKR",
    isInStock: true,
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    imageUrl: "/dew_plus_32_tv.png",
    specifications: JSON.stringify({
      "Screen Size": "32 inches",
      Resolution: "1366 × 768 HD",
      "Operating System": "Android TV 11",
      Sound: "10W Stereo Speakers",
      Connectivity: "WiFi, Bluetooth 5.0, 2× HDMI, 2× USB",
      "Refresh Rate": "60 Hz",
      "Panel Type": "VA",
      HDR: "HDR10",
      "Power Consumption": "45W",
      Warranty: "1 year",
    }),
  },
  {
    id: 5,
    slug: "dew-plus-43-4k-smart-tv",
    name: 'Dew Plus 43" 4K UHD Smart TV',
    shortDescription: "43-inch 4K UHD Android TV with Dolby Audio",
    description:
      'Upgrade your home cinema experience with the Dew Plus 43" 4K UHD Smart TV. Featuring a stunning 4K Ultra HD display with HDR10 and HLG support, every scene comes alive with breathtaking clarity. Dolby Audio and a 20W speaker system fill your room with immersive sound. Android TV gives you access to 10,000+ apps, and the built-in Chromecast lets you cast content directly from your phone. A truly premium TV at a Sri Lankan price.',
    brandName: "Dew Plus",
    brandId: 2,
    categoryId: 2,
    category: "Smart TVs",
    basePrice: "89900.00",
    salePrice: "79900.00",
    discount: 11,
    currency: "LKR",
    isInStock: true,
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    imageUrl: "/dew_plus_43_tv.png",
    specifications: JSON.stringify({
      "Screen Size": "43 inches",
      Resolution: "3840 × 2160 4K UHD",
      "Operating System": "Android TV 11",
      Sound: "20W Dolby Audio",
      Connectivity: "WiFi, Bluetooth 5.0, 3× HDMI, 2× USB, Chromecast",
      "Refresh Rate": "60 Hz",
      "Panel Type": "IPS",
      HDR: "HDR10, HLG",
      "Power Consumption": "75W",
      Warranty: "1 year",
    }),
  },
  {
    id: 6,
    slug: "dew-plus-55-4k-smart-tv",
    name: 'Dew Plus 55" 4K UHD Smart TV',
    shortDescription: "55-inch 4K cinematic experience with surround sound",
    description:
      'The Dew Plus 55" 4K Smart TV is the crown jewel of our television lineup. Its large 55-inch 4K display with Dolby Vision delivers cinema-grade picture quality, while the 30W Dolby Atmos sound system surrounds you in rich, three-dimensional audio. The bezel-less design and ultra-thin profile make it a statement piece in any room. With 4 HDMI ports, ARC support, and Google Assistant built in, this is the smart TV experience redefined for Sri Lanka.',
    brandName: "Dew Plus",
    brandId: 2,
    categoryId: 2,
    category: "Smart TVs",
    basePrice: "149900.00",
    salePrice: "134900.00",
    discount: 10,
    currency: "LKR",
    isInStock: true,
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    imageUrl: "/dew_plus_55_tv.png",
    specifications: JSON.stringify({
      "Screen Size": "55 inches",
      Resolution: "3840 × 2160 4K UHD",
      "Operating System": "Android TV 11 + Google Assistant",
      Sound: "30W Dolby Atmos",
      Connectivity: "WiFi, Bluetooth 5.0, 4× HDMI (ARC), 3× USB, Chromecast",
      "Refresh Rate": "60 Hz",
      "Panel Type": "VA (Bezel-less)",
      HDR: "Dolby Vision, HDR10+, HLG",
      "Power Consumption": "110W",
      Warranty: "2 years",
    }),
  },
  {
    id: 7,
    slug: "dew-plus-ac-1ton-inverter",
    name: "DEW+ 1 Ton Inverter Split AC",
    shortDescription: "Energy-efficient 1 Ton inverter AC with R32 gas",
    description:
      "The DEW+ 1 Ton Inverter Split AC is designed to keep small to medium rooms cool and comfortable while consuming minimal electricity. Using eco-friendly R32 refrigerant and an advanced inverter compressor, it adjusts its power output based on room conditions — delivering up to 60% energy savings over conventional ACs. The auto-clean function keeps the indoor unit hygienic, and the WiFi-enabled remote control lets you manage your comfort from anywhere. Perfect for bedrooms and home offices.",
    brandName: "DEW+ AC",
    brandId: 3,
    categoryId: 3,
    category: "Air Conditioners",
    basePrice: "135000.00",
    salePrice: "124900.00",
    discount: 7,
    currency: "LKR",
    isInStock: true,
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    imageUrl: "/dew_plus_ac_1ton.png",
    specifications: JSON.stringify({
      Capacity: "1 Ton (12,000 BTU)",
      Refrigerant: "R32 (Eco-Friendly)",
      "Energy Rating": "5 Star Inverter",
      "Cooling Area": "Up to 120 sq. ft.",
      "Compressor Warranty": "5 years",
      "Auto Clean": "Yes",
      WiFi: "Yes (Smart Control)",
      "Noise Level": "19 dB (Indoor)",
      "Power Consumption": "900W",
      Warranty: "1 year (unit), 5 years (compressor)",
    }),
  },
  {
    id: 8,
    slug: "dew-plus-ac-1-5ton-inverter",
    name: "DEW+ 1.5 Ton Inverter Split AC",
    shortDescription: "Powerful 1.5 Ton inverter AC for medium rooms",
    description:
      "Keep medium-sized living rooms and offices cool all year with the DEW+ 1.5 Ton Inverter Split AC. Its high-efficiency inverter compressor and R32 refrigerant ensure rapid cooling while keeping electricity bills low. The 4-way airflow system distributes cool air evenly across the room, while the built-in air purifier with anti-bacterial filter ensures the air you breathe is clean and fresh. Features include auto-restart, sleep mode, and a programmable timer for hassle-free operation.",
    brandName: "DEW+ AC",
    brandId: 3,
    categoryId: 3,
    category: "Air Conditioners",
    basePrice: "175000.00",
    salePrice: "159900.00",
    discount: 9,
    currency: "LKR",
    isInStock: true,
    isFeatured: true,
    isBestSeller: false,
    isNew: false,
    imageUrl: "/dew_plus_ac_1_5ton.png",
    specifications: JSON.stringify({
      Capacity: "1.5 Ton (18,000 BTU)",
      Refrigerant: "R32 (Eco-Friendly)",
      "Energy Rating": "5 Star Inverter",
      "Cooling Area": "Up to 180 sq. ft.",
      "Compressor Warranty": "5 years",
      "4-Way Airflow": "Yes",
      "Air Purifier": "Anti-bacterial Filter",
      "Noise Level": "21 dB (Indoor)",
      "Power Consumption": "1400W",
      Warranty: "1 year (unit), 5 years (compressor)",
    }),
  },
  {
    id: 9,
    slug: "dew-plus-ac-2ton-inverter",
    name: "DEW+ 2 Ton Inverter Split AC",
    shortDescription: "Heavy-duty 2 Ton inverter AC for large spaces",
    description:
      "The DEW+ 2 Ton Inverter Split AC is built for large halls, open-plan offices, and commercial spaces that demand serious cooling power. With a 24,000 BTU capacity, it rapidly cools areas up to 250 sq. ft. while the advanced inverter technology ensures you pay the least amount on your electricity bill. The turbo cool function brings the room to your desired temperature in minutes, while the self-cleaning evaporator maintains peak performance year-round.",
    brandName: "DEW+ AC",
    brandId: 3,
    categoryId: 3,
    category: "Air Conditioners",
    basePrice: "225000.00",
    salePrice: "209900.00",
    discount: 7,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    imageUrl: "/dew_plus_ac_2ton.png",
    specifications: JSON.stringify({
      Capacity: "2 Ton (24,000 BTU)",
      Refrigerant: "R32 (Eco-Friendly)",
      "Energy Rating": "4 Star Inverter",
      "Cooling Area": "Up to 250 sq. ft.",
      "Compressor Warranty": "5 years",
      "Turbo Cool": "Yes",
      "Self-Cleaning": "Evaporator Auto-Clean",
      "Noise Level": "24 dB (Indoor)",
      "Power Consumption": "2100W",
      Warranty: "1 year (unit), 5 years (compressor)",
    }),
  },
  {
    id: 10,
    slug: "manju-dew-super-ro-purifier",
    name: "Manju Dew Super RO Water Purifier",
    shortDescription: "7-stage RO water purifier with mineral enrichment",
    description:
      "The Manju Dew Super RO Water Purifier uses advanced 7-stage filtration — including sediment, pre-carbon, RO membrane, UV sterilisation, post-carbon, mineraliser, and UF membrane stages — to deliver water that is 99.9% free of bacteria, viruses, heavy metals, and dissolved solids. The mineral enrichment stage adds back essential calcium and magnesium for healthier, better-tasting water. With a 10-litre storage tank and 200 GPD purification capacity, it handles a family's daily needs with ease.",
    brandName: "Manju Dew Super",
    brandId: 4,
    categoryId: 4,
    category: "Water Filters",
    basePrice: "45000.00",
    salePrice: "39900.00",
    discount: 11,
    currency: "LKR",
    isInStock: true,
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    imageUrl: "/ro_water_purifier.png",
    specifications: JSON.stringify({
      Technology: "RO + UV + UF + Mineraliser",
      Stages: "7-stage filtration",
      Capacity: "10 Litre storage tank",
      "Purification Rate": "200 GPD",
      "TDS Reduction": "Up to 98%",
      "Bacteria Removal": "99.9%",
      "UV Sterilisation": "Yes",
      "Mineral Enrichment": "Yes (Ca, Mg)",
      "Power Consumption": "45W",
      Warranty: "1 year",
    }),
  },
  {
    id: 11,
    slug: "manju-dew-super-hot-cold-dispenser",
    name: "Manju Dew Super Hot & Cold Dispenser",
    shortDescription: "RO purifier with hot and cold water dispenser",
    description:
      "The Manju Dew Super Hot & Cold Dispenser combines advanced RO purification with the convenience of instant hot and cold water. Perfect for offices, homes, and reception areas, it delivers chilled water at 4–10°C and piping hot water at 85–95°C at the press of a button — all purified through its 7-stage RO system. The child-safety lock on the hot water tap ensures family safety, while the stainless steel tank prevents bacterial growth. A complete hydration solution for the modern Sri Lankan home.",
    brandName: "Manju Dew Super",
    brandId: 4,
    categoryId: 4,
    category: "Water Filters",
    basePrice: "65000.00",
    salePrice: "58900.00",
    discount: 9,
    currency: "LKR",
    isInStock: true,
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    imageUrl:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=400&q=80",
    specifications: JSON.stringify({
      Technology: "RO + UV + UF",
      Stages: "7-stage filtration",
      "Cold Water Temp": "4–10°C",
      "Hot Water Temp": "85–95°C",
      Capacity: "Cold tank: 5L / Hot tank: 1.5L",
      "Purification Rate": "200 GPD",
      "Child Safety Lock": "Yes (hot tap)",
      "Tank Material": "Stainless Steel",
      "Power Consumption": "500W (heating)",
      Warranty: "1 year",
    }),
  },
  {
    id: 12,
    slug: "manju-cr-200-pages",
    name: "Manju CR 200 Pages Exercise Book",
    shortDescription: "200-page CR ruled exercise book for students",
    description:
      "The Manju CR 200 Pages Exercise Book is the trusted companion of Sri Lankan students from Grade 1 through A/Levels. Made from 60 GSM wood-free paper with crisp, consistent ruling, it's easy on the eyes and comfortable to write on for hours. The durable 200 GSM card cover resists tearing and moisture, keeping your notes safe all year long. Available in packs of 10 for school bulk purchases — the most affordable quality exercise book in Sri Lanka.",
    brandName: "Manju Exercise Books",
    brandId: 5,
    categoryId: 5,
    category: "Exercise Books",
    basePrice: "180.00",
    salePrice: null,
    discount: 0,
    currency: "LKR",
    isInStock: true,
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    imageUrl:
      "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=400&q=80",
    specifications: JSON.stringify({
      Pages: "200 pages",
      Ruling: "CR (Continuous Ruling)",
      Size: "A4 (210 × 297 mm)",
      "Paper GSM": "60 GSM Wood-Free",
      Cover: "200 GSM Hard Card Cover",
      "Cover Finish": "Laminated Gloss",
      Colour: "Blue / Red / Green (assorted)",
      "Pack Size": "1 book",
      "Suitable For": "All grades",
      "Made In": "Sri Lanka",
    }),
  },
  {
    id: 13,
    slug: "manju-single-ruled-120-pages",
    name: "Manju Single Ruled 120 Pages",
    shortDescription: "120-page single ruled exercise book",
    description:
      "The Manju Single Ruled 120 Pages exercise book is perfect for primary and secondary school students who need a neat, manageable notebook for daily classwork. Single ruling with a left margin makes it ideal for English, Sinhala, Tamil, and all language subjects. Smooth 60 GSM paper prevents ink bleed-through, whether you're using a ballpoint pen or fountain pen. Lightweight and affordable — the go-to choice for Sri Lankan parents and teachers alike.",
    brandName: "Manju Exercise Books",
    brandId: 5,
    categoryId: 5,
    category: "Exercise Books",
    basePrice: "120.00",
    salePrice: null,
    discount: 0,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    imageUrl:
      "https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=400&q=80",
    specifications: JSON.stringify({
      Pages: "120 pages",
      Ruling: "Single Ruled with Margin",
      Size: "A4 (210 × 297 mm)",
      "Paper GSM": "60 GSM Wood-Free",
      Cover: "180 GSM Card Cover",
      "Cover Finish": "Matt Laminate",
      Colour: "Assorted",
      "Pack Size": "1 book",
      "Suitable For": "Grade 1–11",
      "Made In": "Sri Lanka",
    }),
  },
  {
    id: 14,
    slug: "manju-square-ruled-80-pages",
    name: "Manju Square Ruled 80 Pages",
    shortDescription: "80-page square ruled book for math and science",
    description:
      "The Manju Square Ruled 80 Pages exercise book is specifically designed for Mathematics, Science, and Technical subjects where accurate graphs and diagrams are essential. The 5mm square ruling on 60 GSM paper allows precise grid work without the paper warping or tearing. Compact and lightweight, it's easy to carry between classes. Trusted by mathematics teachers across Sri Lanka's national schools for over two decades.",
    brandName: "Manju Exercise Books",
    brandId: 5,
    categoryId: 5,
    category: "Exercise Books",
    basePrice: "95.00",
    salePrice: null,
    discount: 0,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    imageUrl:
      "https://images.unsplash.com/photo-1519406596751-0a3ccc4937ef?auto=format&fit=crop&w=400&q=80",
    specifications: JSON.stringify({
      Pages: "80 pages",
      Ruling: "5mm Square Grid",
      Size: "A4 (210 × 297 mm)",
      "Paper GSM": "60 GSM Wood-Free",
      Cover: "160 GSM Card Cover",
      "Cover Finish": "Matt Laminate",
      Colour: "Blue / Green",
      "Pack Size": "1 book",
      "Suitable For": "Maths, Science, Technical",
      "Made In": "Sri Lanka",
    }),
  },
  {
    id: 15,
    slug: "manju-drawing-book-40-pages",
    name: "Manju Drawing Book 40 Pages",
    shortDescription: "40-page unruled drawing book for art class",
    description:
      "The Manju Drawing Book is the creative canvas every young artist needs. With 40 pages of thick 80 GSM unruled paper, it's perfect for pencil sketching, watercolour, crayon, and poster paint work. The sturdy 250 GSM hard cover keeps artwork safe, while the white inner pages ensure true colour reproduction. Recommended by Art teachers in Sri Lanka's national and international schools. Available in A4 size — the standard for O/Level Art submissions.",
    brandName: "Manju Exercise Books",
    brandId: 5,
    categoryId: 5,
    category: "Exercise Books",
    basePrice: "150.00",
    salePrice: "130.00",
    discount: 13,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    imageUrl:
      "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=400&q=80",
    specifications: JSON.stringify({
      Pages: "40 pages",
      Ruling: "Unruled (Plain White)",
      Size: "A4 (210 × 297 mm)",
      "Paper GSM": "80 GSM Drawing Paper",
      Cover: "250 GSM Hard Cover",
      "Cover Finish": "Gloss Laminate",
      Colour: "White interior",
      "Pack Size": "1 book",
      "Suitable For": "Art, Drawing, O/Level Art",
      "Made In": "Sri Lanka",
    }),
  },
];
