export const STATIC_BRANDS = [
  {
    id: 1,
    slug: "dew-motors",
    name: "Dew Motors",
    tagline: "Power Your Ride, Go Electric",
    description:
      "Dew Motors is Sri Lanka's leading electric motorcycle brand, offering eco-friendly, powerful electric bikes designed for daily commuting and adventure. With cutting-edge battery technology and sleek designs, Dew Motors is driving the future of sustainable transportation in Sri Lanka.",
    primaryColor: "#0ea5e9",
    accentColor: "#38bdf8",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 2,
    slug: "dew-plus",
    name: "Dew Plus",
    tagline: "Crystal Clear Entertainment",
    description:
      'Dew Plus brings premium 4K Android Smart TVs with built-in streaming apps, crystal clear displays, and immersive sound systems. Available in 32" to 65" sizes, perfect for every Sri Lankan home.',
    primaryColor: "#8b5cf6",
    accentColor: "#a78bfa",
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 3,
    slug: "dew-plus-ac",
    name: "DEW+ AC",
    tagline: "Cool Comfort, Smart Living",
    description:
      "DEW+ AC offers energy-efficient inverter split air conditioners with R32 eco-friendly refrigerant. Available in 1 Ton, 1.5 Ton, and 2 Ton capacities with smart WiFi control, turbo cooling, and 5-year compressor warranty.",
    primaryColor: "#06b6d4",
    accentColor: "#22d3ee",
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 4,
    slug: "manju-dew-super",
    name: "Manju Dew Super",
    tagline: "Pure Water, Healthy Life",
    description:
      "Manju Dew Super water purifiers use advanced RO, UV, and UF filtration technology to deliver clean, safe drinking water. Available in multiple models including hot & cold dispensers, perfect for homes and offices.",
    primaryColor: "#3b82f6",
    accentColor: "#60a5fa",
    sortOrder: 4,
    isActive: true,
  },
];

export const STATIC_PRODUCTS = [
  {
    id: 38,
    slug: "dew-super-ro-water-filter",
    sku: "MNJ-04-04-038",
    name: "Dew Super RO Water Filter",
    brandName: "Manju Dew Super",
    brandId: 4,
    categoryId: 4,
    category: "Water Filters",
    basePrice: "69900.00",
    salePrice: null,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    imageUrl: "/ro_water_purifier.webp",
    specifications:
      '{"01. Stage":"05 Micron Sediment Filter (Above 05 Micron Removes Sediment In Water)","02. Stage":"01 Micron Sediment Filter (Above 01 Micron Removes Sediment In Water)","03. Stage":"Activated Carbon Filter","04. Stage":"Ro Membrane (Only Pure Water Is Filterd)","05. Stage":"Mineral Cartridge","06. Stage":"UV Sterilizer (Destroys Bacteria & Viruses In The Water)","Feature 4":"* High Removal Capacity Of Iron Manganese H2s Aresenic & Heavy Mentals","Feature 5":"* Removes Organizes Bacteria & Color","Feature 6":"* Removes Chlorine","Feature 7":"* Enhances Test Of Water","Feature 10":"* Adds Essential Minerals Like Calcium, Magnesium, Sodium & Potassium.","Feature 11":"* Increase PH & Makes Alkaline Water.","Feature 13":"07. The capacity is 100 liters per day","Sub Category":"RO Water Filter","Installment Plan":"Down Payment - Rs.14900\\nMonthly premium - Rs.6000 X 11 (Months)\\n                                    Rs.4000 X 01 (Month)","Installment Price":"Rs. 84,900"}',
    description:
      "One year warranty\nLong term maintenance service after warranty period\nFree shipping and installation\nFree water test\nFree after sale service\nAvailability of all spare parts\n22 years of experienced entrepreneurship\nEasy payment methods in installments\nFree water testing",
    shortDescription: "One year warranty",
    warrantyMonths: 24,
  },
  {
    id: 39,
    slug: "dew-super-ro-water-filter-1",
    sku: "MNJ-04-04-039",
    name: "Dew Super RO+ Water Filter",
    brandName: "Manju Dew Super",
    brandId: 4,
    categoryId: 4,
    category: "Water Filters",
    basePrice: "74900.00",
    salePrice: null,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    imageUrl: "/ro_water_purifier.webp",
    specifications:
      '{"01. Stage":"05 Micron Sediment Filter (Above 05 Micron Removes Sediment In Water)","02. Stage":"01 Micron Sediment Filter (Above 01 Micron Removes Sediment In Water)","03. Stage":"Activated Carbon Filter","04. Stage":"Ro Membrane (Only Pure Water Is Filterd)","05. Stage":"Mineral Cartridge","06. Stage":"UV Sterilizer (Destroys Bacteria & Viruses In The Water)","Feature 4":"* High Removal Capacity Of Iron Manganese H2s Aresenic & Heavy Mentals","Feature 5":"* Removes Organizes Bacteria & Color","Feature 6":"* Removes Chlorine","Feature 7":"* Enhances Test Of Water","Feature 10":"* Adds Essential Minerals Like Calcium, Magnesium, Sodium & Potassium.","Feature 11":"* Increase PH & Makes Alkaline Water.","Feature 13":"07. The capacity is 100 liters per day","Sub Category":"RO+ Water Filter","Installment Plan":"Down Payment - Rs.14900\\nMonthly premium - Rs.6250 X 12 (Months)","Installment Price":"Rs. 89,900"}',
    description:
      "One year warranty\nLong term maintenance service after warranty period\nFree shipping and installation\nFree water test\nFree after sale service\nAvailability of all spare parts\n22 years of experienced entrepreneurship\nEasy payment methods in installments\nFree water testing",
    shortDescription: "One year warranty",
    warrantyMonths: 24,
  },
  {
    id: 40,
    slug: "dew-super-hot-normal-water-filter",
    sku: "MNJ-04-04-040",
    name: "Dew Super Hot & Normal Water Filter",
    brandName: "Manju Dew Super",
    brandId: 4,
    categoryId: 4,
    category: "Water Filters",
    basePrice: "86900.00",
    salePrice: null,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    imageUrl: "/ro_water_purifier.webp",
    specifications:
      '{"01. Stage":"05 Micron Sediment Filter (Above 05 Micron Removes Sediment In Water)","02. Stage":"01 Micron Sediment Filter (Above 01 Micron Removes Sediment In Water)","03. Stage":"Activated Carbon Filter","04. Stage":"Ro Membrane (Only Pure Water Is Filterd)","05. Stage":"Mineral Cartridge","06. Stage":"UV Sterilizer (Destroys Bacteria & Viruses In The Water)","Feature 4":"* High Removal Capacity Of Iron Manganese H2s Aresenic & Heavy Mentals","Feature 5":"* Removes Organizes Bacteria & Color","Feature 6":"* Removes Chlorine","Feature 7":"* Enhances Test Of Water","Feature 10":"* Adds Essential Minerals Like Calcium, Magnesium, Sodium & Potassium.","Feature 11":"* Increase PH & Makes Alkaline Water.","Feature 13":"07. The capacity is 75 liters per day","Sub Category":"Hot & Normal Water Filter","Installment Plan":"Down Payment - Rs.19900\\nMonthly premium - Rs.6250 X 12 (Months)","Installment Price":"Rs. 94,900"}',
    description:
      "One year warranty\nLong term maintenance service after warranty period\nFree shipping and installation\nFree water test\nFree after sale service\nAvailability of all spare parts\n22 years of experienced entrepreneurship\nEasy payment methods in installments\nFree water testing",
    shortDescription: "One year warranty",
    warrantyMonths: 24,
  },
  {
    id: 41,
    slug: "dew-super-hotcool-normal-water-filter",
    sku: "MNJ-04-04-041",
    name: "Dew Super Hot,Cool & Normal Water Filter",
    brandName: "Manju Dew Super",
    brandId: 4,
    categoryId: 4,
    category: "Water Filters",
    basePrice: "89900.00",
    salePrice: null,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    imageUrl: "/ro_water_purifier.webp",
    specifications:
      '{"01. Stage":"05 Micron Sediment Filter (Above 05 Micron Removes Sediment In Water)","02. Stage":"01 Micron Sediment Filter (Above 01 Micron Removes Sediment In Water)","03. Stage":"Activated Carbon Filter","04. Stage":"Ro Membrane (Only Pure Water Is Filterd)","05. Stage":"Mineral Cartridge","06. Stage":"UV Sterilizer (Destroys Bacteria & Viruses In The Water)","Feature 4":"* High Removal Capacity Of Iron Manganese H2s Aresenic & Heavy Mentals","Feature 5":"* Removes Organizes Bacteria & Color","Feature 6":"* Removes Chlorine","Feature 7":"* Enhances Test Of Water","Feature 10":"* Adds Essential Minerals Like Calcium, Magnesium, Sodium & Potassium.","Feature 11":"* Increase PH & Makes Alkaline Water.","Feature 13":"07. The capacity is 75 liters per day","Sub Category":"Hot,Cool & Normal Water Filter","Installment Plan":"Down Payment - Rs.22900\\nMonthly premium - Rs.6250 X 12 (Months)","Installment Price":"Rs. 97,900"}',
    description:
      "One year warranty\nLong term maintenance service after warranty period\nFree shipping and installation\nFree water test\nFree after sale service\nAvailability of all spare parts\n22 years of experienced entrepreneurship\nEasy payment methods in installments\nFree water testing",
    shortDescription: "One year warranty",
    warrantyMonths: 24,
  },
  {
    id: 42,
    slug: "dew-super-commercial-water-filter-500l",
    sku: "MNJ-04-04-042",
    name: "Dew Super Commercial Water Filter 500L",
    brandName: "Manju Dew Super",
    brandId: 4,
    categoryId: 4,
    category: "Water Filters",
    basePrice: "175000.00",
    salePrice: null,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    imageUrl: "/ro_water_purifier.webp",
    specifications:
      '{"01. Stage":"05 Micron Sediment Filter (Above 05 Micron Removes Sediment In Water)","02. Stage":"01 Micron Sediment Filter (Above 01 Micron Removes Sediment In Water)","03. Stage":"Activated Carbon Filter","04. Stage":"Ro Membrane (Only Pure Water Is Filterd)","05. Stage":"Mineral Cartridge","06. Stage":"UV Sterilizer (Destroys Bacteria & Viruses In The Water)","Feature 4":"* High Removal Capacity Of Iron Manganese H2s Aresenic & Heavy Mentals","Feature 5":"* Removes Organizes Bacteria & Color","Feature 6":"* Removes Chlorine","Feature 7":"* Enhances Test Of Water","Feature 10":"* Adds Essential Minerals Like Calcium, Magnesium, Sodium & Potassium.","Feature 11":"* Increase PH & Makes Alkaline Water.","Feature 13":"07. The capacity is 500 liters per day","Sub Category":"Commercial Water Filter","Installment Plan":"Down Payment - Rs.90000\\nMonthly premium - Rs.17500 X 06 (Months)","Installment Price":"Rs. 195,000"}',
    description:
      "One year warranty\nLong term maintenance service after warranty period\nFree shipping and installation\nFree water test\nFree after sale service\nAvailability of all spare parts\n22 years of experienced entrepreneurship\nEasy payment methods in installments\nFree water testing",
    shortDescription: "One year warranty",
    warrantyMonths: 24,
  },
  {
    id: 43,
    slug: "dew-super-commercial-water-filter-2500l",
    sku: "MNJ-04-04-043",
    name: "Dew Super Commercial Water Filter 2500L",
    brandName: "Manju Dew Super",
    brandId: 4,
    categoryId: 4,
    category: "Water Filters",
    basePrice: "315000.00",
    salePrice: null,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    imageUrl: "/ro_water_purifier.webp",
    specifications:
      '{"01. Stage":"05 Micron Sediment Filter (Above 05 Micron Removes Sediment In Water)","02. Stage":"01 Micron Sediment Filter (Above 01 Micron Removes Sediment In Water)","03. Stage":"Activated Carbon Filter","04. Stage":"Ro Membrane (Only Pure Water Is Filterd)","05. Stage":"Mineral Cartridge","06. Stage":"UV Sterilizer (Destroys Bacteria & Viruses In The Water)","Feature 4":"* High Removal Capacity Of Iron Manganese H2s Aresenic & Heavy Mentals","Feature 5":"* Removes Organizes Bacteria & Color","Feature 6":"* Removes Chlorine","Feature 7":"* Enhances Test Of Water","Feature 10":"* Adds Essential Minerals Like Calcium, Magnesium, Sodium & Potassium.","Feature 11":"* Increase PH & Makes Alkaline Water.","Feature 13":"07. The capacity is 2500 liters per day","Sub Category":"Commercial Water Filter","Installment Plan":"Down Payment - Rs.170000\\nMonthly premium - Rs.30000 X 06 (Months)","Installment Price":"Rs. 350,000"}',
    description:
      "One year warranty\nLong term maintenance service after warranty period\nFree shipping and installation\nFree water test\nFree after sale service\nAvailability of all spare parts\n22 years of experienced entrepreneurship\nEasy payment methods in installments\nFree water testing",
    shortDescription: "One year warranty",
    warrantyMonths: 24,
  },
  {
    id: 44,
    slug: "dew-super-commercial-water-filter-3000l",
    sku: "MNJ-04-04-044",
    name: "Dew Super Commercial Water Filter 3000L",
    brandName: "Manju Dew Super",
    brandId: 4,
    categoryId: 4,
    category: "Water Filters",
    basePrice: "400000.00",
    salePrice: null,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    imageUrl: "/ro_water_purifier.webp",
    specifications:
      '{"01. Stage":"05 Micron Sediment Filter (Above 05 Micron Removes Sediment In Water)","02. Stage":"01 Micron Sediment Filter (Above 01 Micron Removes Sediment In Water)","03. Stage":"Activated Carbon Filter","04. Stage":"Ro Membrane (Only Pure Water Is Filterd)","05. Stage":"Mineral Cartridge","06. Stage":"UV Sterilizer (Destroys Bacteria & Viruses In The Water)","Feature 4":"* High Removal Capacity Of Iron Manganese H2s Aresenic & Heavy Mentals","Feature 5":"* Removes Organizes Bacteria & Color","Feature 6":"* Removes Chlorine","Feature 7":"* Enhances Test Of Water","Feature 10":"* Adds Essential Minerals Like Calcium, Magnesium, Sodium & Potassium.","Feature 11":"* Increase PH & Makes Alkaline Water.","Feature 13":"07. The capacity is 3000 liters per day","Sub Category":"Commercial Water Filter","Installment Plan":"Down Payment - Rs.225000\\nMonthly premium - Rs.37500 X 06 (Months)","Installment Price":"Rs. 450,000"}',
    description:
      "One year warranty\nLong term maintenance service after warranty period\nFree shipping and installation\nFree water test\nFree after sale service\nAvailability of all spare parts\n22 years of experienced entrepreneurship\nEasy payment methods in installments\nFree water testing",
    shortDescription: "One year warranty",
    warrantyMonths: 24,
  },
  {
    id: 45,
    slug: "dew-plus-smart-tv-32",
    sku: "MNJ-02-02-045",
    name: "Dew Plus (+) Smart Tv 32''",
    brandName: "Dew Plus",
    brandId: 2,
    categoryId: 2,
    category: "Smart TVs",
    basePrice: "74400.00",
    salePrice: null,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    imageUrl: "/dew_plus_32_tv.webp",
    specifications:
      '{"Feature 1":"LED TV","Feature 2":"Wifi","Feature 3":"Full HD 1080","Feature 4":"Android 12","Feature 5":"Youtube","Feature 6":"Connect Share Movie","Feature 7":"USB Support","Feature 8":"Energy Saving","Feature 9":"Stereo Clear Voice","Sub Category":"Smart Tv","Installment Plan":"Down Payment - Rs.10000\\nMonthly premium - Rs.6200 X 12 (Months)","Installment Price":"Rs. 84,400"}',
    description:
      "One year warranty period\nFree after sales service\nOne TV per TV during the warranty period\n22 years of cardamom entrepreneurship\nAvailability of all spare parts\nEasy payment method in installments",
    shortDescription: "One year warranty period",
    warrantyMonths: 24,
  },
  {
    id: 46,
    slug: "dew-plus-smart-tv-43",
    sku: "MNJ-02-02-046",
    name: "Dew Plus (+) Smart Tv 43''",
    brandName: "Dew Plus",
    brandId: 2,
    categoryId: 2,
    category: "Smart TVs",
    basePrice: "99800.00",
    salePrice: null,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    imageUrl: "/dew_plus_43_tv.webp",
    specifications:
      '{"Feature 1":"LED TV","Feature 2":"Wifi","Feature 3":"Full HD 1080","Feature 4":"Android 12","Feature 5":"Youtube","Feature 6":"Connect Share Movie","Feature 7":"USB Support","Feature 8":"Energy Saving","Feature 9":"Stereo Clear Voice","Sub Category":"Smart Tv","Installment Plan":"Down Payment - Rs.15000\\nMonthly premium - Rs.9150 X 12 (Months)","Installment Price":"Rs. 124,800"}',
    description:
      "One year warranty period\nFree after sales service\nOne TV per TV during the warranty period\n22 years of cardamom entrepreneurship\nAvailability of all spare parts\nEasy payment method in installments",
    shortDescription: "One year warranty period",
    warrantyMonths: 24,
  },
  {
    id: 47,
    slug: "dew-plus-smart-tv-55",
    sku: "MNJ-02-02-047",
    name: "Dew Plus (+) Smart Tv 55''",
    brandName: "Dew Plus",
    brandId: 2,
    categoryId: 2,
    category: "Smart TVs",
    basePrice: "169500.00",
    salePrice: null,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    imageUrl: "/dew_plus_55_tv.webp",
    specifications:
      '{"Feature 1":"LED TV","Feature 2":"Wifi","Feature 3":"4K Ultra HD","Feature 4":"Android 12","Feature 5":"Youtube","Feature 6":"Connect Share Movie","Feature 7":"USB Support","Feature 8":"Energy Saving","Feature 9":"Stereo Clear Voice","Sub Category":"Smart Tv","Installment Plan":"Down Payment - Rs.25000\\nMonthly premium - Rs.10250 X 18 (Months)","Installment Price":"Rs. 209,500"}',
    description:
      "One year warranty period\nFree after sales service\nOne TV per TV during the warranty period\n22 years of cardamom entrepreneurship\nAvailability of all spare parts\nEasy payment method in installments",
    shortDescription: "One year warranty period",
    warrantyMonths: 24,
  },
  {
    id: 48,
    slug: "dew-plus-smart-tv-65",
    sku: "MNJ-02-02-048",
    name: "Dew Plus (+) Smart Tv 65''",
    brandName: "Dew Plus",
    brandId: 2,
    categoryId: 2,
    category: "Smart TVs",
    basePrice: "237800.00",
    salePrice: null,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    imageUrl: "/dew_plus_65_tv.webp",
    specifications:
      '{"Feature 1":"LED TV","Feature 2":"Wifi","Feature 3":"4K Ultra HD","Feature 4":"Android 12","Feature 5":"Youtube","Feature 6":"Connect Share Movie","Feature 7":"USB Support","Feature 8":"Energy Saving","Feature 9":"Stereo Clear Voice","Sub Category":"Smart Tv","Installment Plan":"Down Payment - Rs.35000\\nMonthly premium - Rs.10950 X 24 (Months)","Installment Price":"Rs. 297,800"}',
    description:
      "One year warranty period\nFree after sales service\nOne TV per TV during the warranty period\n22 years of cardamom entrepreneurship\nAvailability of all spare parts\nEasy payment method in installments",
    shortDescription: "One year warranty period",
    warrantyMonths: 24,
  },
  {
    id: 49,
    slug: "dew-plus-smart-tv-75",
    sku: "MNJ-02-02-049",
    name: "Dew Plus (+) Smart Tv 75''",
    brandName: "Dew Plus",
    brandId: 2,
    categoryId: 2,
    category: "Smart TVs",
    basePrice: "468800.00",
    salePrice: null,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    imageUrl: "/dew_plus_75_tv.webp",
    specifications:
      '{"Feature 1":"LED TV","Feature 2":"Wifi","Feature 3":"4K Ultra HD","Feature 4":"Android 12","Feature 5":"Youtube","Feature 6":"Connect Share Movie","Feature 7":"USB Support","Feature 8":"Energy Saving","Feature 9":"Stereo Clear Voice","Sub Category":"Smart Tv","Installment Plan":"Down Payment - Rs.50000\\nMonthly premium - Rs.19950 X 24 (Months)","Installment Price":"Rs. 528,800"}',
    description:
      "One year warranty period\nFree after sales service\nOne TV per TV during the warranty period\n22 years of cardamom entrepreneurship\nAvailability of all spare parts\nEasy payment method in installments",
    shortDescription: "One year warranty period",
    warrantyMonths: 24,
  },
  {
    id: 50,
    slug: "dew-plus-smart-tv-98",
    sku: "MNJ-02-02-050",
    name: "Dew Plus (+) Smart Tv 98''",
    brandName: "Dew Plus",
    brandId: 2,
    categoryId: 2,
    category: "Smart TVs",
    basePrice: "888800.00",
    salePrice: null,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    imageUrl: "/dew_plus_98_tv.webp",
    specifications:
      '{"Feature 1":"LED TV","Feature 2":"Wifi","Feature 3":"4K Ultra HD","Feature 4":"Android 12","Feature 5":"Youtube","Feature 6":"Connect Share Movie","Feature 7":"USB Support","Feature 8":"Energy Saving","Feature 9":"Stereo Clear Voice","Sub Category":"Smart Tv","Installment Plan":"Down Payment - Rs.100000\\nMonthly premium - Rs.37400 X 24 (Months)","Installment Price":"Rs. 997,600"}',
    description:
      "One year warranty period\nFree after sales service\nOne TV per TV during the warranty period\n22 years of cardamom entrepreneurship\nAvailability of all spare parts\nEasy payment method in installments",
    shortDescription: "One year warranty period",
    warrantyMonths: 24,
  },
  {
    id: 51,
    slug: "dew-motors-yw06-2000w",
    sku: "MNJ-01-01-051",
    name: "Dew Motors - YW06 2000W",
    brandName: "Dew Motors",
    brandId: 1,
    categoryId: 1,
    category: "Electric Bikes",
    basePrice: "630000.00",
    salePrice: null,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    imageUrl: "/scooter_silver.webp",
    specifications:
      '{"Feature 1":"Max Speed Is 65KM/H","Feature 2":"Long Life Span","Feature 3":"High/Standard Painting Technology","Feature 4":"Long Distance Range","Feature 5":"Stable & Durable Frame","Feature 6":"Swapped Lithium Battery","Sub Category":"Electric Bike","Installment Plan":"Down Payment - Rs.130000\\nMonthly premium - Rs.20889 X 36 (Months)","Installment Price":"Rs. 882,004"}',
    description:
      "Lowest price in the market\nMaximum savings in all respects\n01 year or 1500km warranty\nAfter sales service\nIsland wide service network\nOver 2 decades of customer trust",
    shortDescription: "Lowest price in the market",
    warrantyMonths: 12,
  },
  {
    id: 52,
    slug: "dew-motors-em005-2400w",
    sku: "MNJ-01-01-052",
    name: "Dew Motors - EM005 2400W",
    brandName: "Dew Motors",
    brandId: 1,
    categoryId: 1,
    category: "Electric Bikes",
    basePrice: "680000.00",
    salePrice: null,
    currency: "LKR",
    isInStock: true,
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    imageUrl: "/scooter_red.webp",
    specifications:
      '{"Feature 1":"Max Speed Is 65KM/H","Feature 2":"Long Life Span","Feature 3":"High/Standard Painting Technology","Feature 4":"Long Distance Range","Feature 5":"Stable & Durable Frame","Feature 6":"Swapped Lithium Battery","Sub Category":"Electric Bike","Installment Plan":"Down Payment - Rs.130000\\nMonthly premium - Rs.26278 X 36 (Months)\\nOr\\nMonthly premium - Rs.33917 X 24 (Months)\\nOr\\nMonthly premium - Rs.56834 X 12 (Months)","Installment Price":"Rs. 957,208"}',
    description:
      "Lowest price in the market\nMaximum savings in all respects\n01 year or 1500km warranty\nAfter sales service\nIsland wide service network\nOver 2 decades of customer trust",
    shortDescription: "Lowest price in the market",
    warrantyMonths: 12,
  },
  {
    id: 53,
    slug: "dew-plus-1-0-ton-inverter-split-ac",
    sku: "MNJ-03-03-001",
    name: "DEW+ 1.0 Ton Inverter Split AC",
    brandName: "DEW+ AC",
    brandId: 3,
    categoryId: 3,
    category: "Air Conditioners",
    basePrice: "145000.00",
    salePrice: null,
    currency: "LKR",
    isInStock: true,
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    imageUrl: "/dew_plus_ac_1ton.webp",
    specifications:
      '{"Capacity":"12,000 BTU (1.0 Ton)","Features":"WiFi Smart Control, Turbo Cooling, 4-Way Air Swing, Anti-Bacterial Filter","Warranty":"5-Year Compressor Warranty, 1-Year Comprehensive","Technology":"Full DC Inverter","Refrigerant":"Eco-Friendly R32"}',
    description:
      "Energy-efficient 1.0 Ton Inverter AC with R32 eco-friendly gas and WiFi smart app control. Free installation and bracket included.",
    shortDescription:
      "Energy-efficient 1.0 Ton Inverter AC with R32 eco-friendly gas and WiFi smart app control. Free installation and bracket included.",
    warrantyMonths: 60,
  },
  {
    id: 54,
    slug: "dew-plus-1-5-ton-inverter-split-ac",
    sku: "MNJ-03-03-002",
    name: "DEW+ 1.5 Ton Inverter Split AC",
    brandName: "DEW+ AC",
    brandId: 3,
    categoryId: 3,
    category: "Air Conditioners",
    basePrice: "185000.00",
    salePrice: null,
    currency: "LKR",
    isInStock: true,
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    imageUrl: "/dew_plus_ac_1_5ton.webp",
    specifications:
      '{"Capacity":"18,000 BTU (1.5 Ton)","Features":"WiFi Smart Control, Turbo Cooling, 4-Way Air Swing, Anti-Bacterial Filter","Warranty":"5-Year Compressor Warranty, 1-Year Comprehensive","Technology":"Full DC Inverter","Refrigerant":"Eco-Friendly R32"}',
    description:
      "High-performance 1.5 Ton Inverter AC designed for medium-to-large rooms with high energy efficiency rating.",
    shortDescription:
      "High-performance 1.5 Ton Inverter AC designed for medium-to-large rooms with high energy efficiency rating.",
    warrantyMonths: 60,
  },
  {
    id: 55,
    slug: "dew-plus-2-0-ton-inverter-split-ac",
    sku: "MNJ-03-03-003",
    name: "DEW+ 2.0 Ton Inverter Split AC",
    brandName: "DEW+ AC",
    brandId: 3,
    categoryId: 3,
    category: "Air Conditioners",
    basePrice: "235000.00",
    salePrice: null,
    currency: "LKR",
    isInStock: true,
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    imageUrl: "/dew_plus_ac_2ton.webp",
    specifications:
      '{"Capacity":"24,000 BTU (2.0 Ton)","Features":"WiFi Smart Control, Turbo Cooling, 4-Way Air Swing, Anti-Bacterial Filter","Warranty":"5-Year Compressor Warranty, 1-Year Comprehensive","Technology":"Full DC Inverter","Refrigerant":"Eco-Friendly R32"}',
    description:
      "Heavy-duty 2.0 Ton Inverter AC for large living rooms, commercial spaces, and showrooms with rapid turbo cooling.",
    shortDescription:
      "Heavy-duty 2.0 Ton Inverter AC for large living rooms, commercial spaces, and showrooms with rapid turbo cooling.",
    warrantyMonths: 60,
  },
];
